#!/usr/bin/env bash

function monitor-coords {
  monitor_spec=$1

  read width height x_offset y_offset < \
       <(echo $monitor_spec | tr '+x' '  ')
  
  topleft_x=$(($x_offset))
  topleft_y=$(($y_offset))
  
  topright_x=$(($x_offset + $width - 1))
  topright_y=$(($y_offset))
  
  bottomleft_x=$(($x_offset))
  bottomleft_y=$(($y_offset + $height - 1))
  
  bottomright_x=$(($x_offset + $width - 1))
  bottomright_y=$(($y_offset + $height - 1))

  echo -n $topleft_x $topleft_y ' '
  echo -n $topright_x $topright_y ' '
  echo -n $bottomleft_x $bottomleft_y ' '
  echo $bottomright_x $bottomright_y 
}

function monitor-specs {
  xrandr | grep ' connected' | grep "[^ ]* (" -o | cut -d ' ' -f 1
}

action="-t 1.5 print -d 200"

[[ "${BASH_SOURCE[0]}" != "${0}" ]] && return # rest of file is not for sourcing

for monitor_spec in $(monitor-specs); do
  echo $monitor_spec
  read topleft_x topleft_y \
       topright_x topright_y \
       bottomleft_x bottomleft_y \
       bottomright_x bottomright_y < <(monitor-coords "$monitor_spec")
  
  ./xfence $topleft_x $topleft_y $topright_x $topright_y +y &
  ./xfence $topright_x $topright_y $bottomright_x $bottomright_y -x &
  ./xfence $bottomright_x $bottomright_y $bottomleft_x $bottomleft_y -y &
  ./xfence $bottomleft_x $bottomleft_y $topleft_x $topleft_y +x &
done

trap 'kill $(jobs -p); exit' INT

wait
